### ISSUE TITLE
In-browser icon

### ISSUE THREAD

**Issue by arturdryomov** [metarmask/dom-distiller-reading-mode#16]
It would be nice to have the icon to be the one from the Material design set. Bubbles look kind of weird, but it might be just me.

It would great to have the icon to be neutral grey by default to fit the Chrome UI better.

**Comment by metarmask** [comment]
I agree with [the documentation](https://developer.chrome.com/extensions/browserAction#tips) which says: "Don't attempt to mimic Google Chrome's monochrome menu icon. That doesn't work well with themes, and anyway, extensions should stand out a little."

When first developing the extension I tried using [the main extension icon](https://github.com/metarmask/dom-distiller-reading-mode/blob/master/src/icons/extension.svg), which actually derives from "chrome_reader_mode" and "bubble_chart", but it was too detailed.

If you don't like that it stands out you can hide it in overflow menu and bind a keyboard shortcut to activate it instead.

Hope that's helpful.

**Comment by arturdryomov** [comment]
Yep, hiding it works for me. Thanks!
