### ISSUE TITLE
Bug: doesn't work on Brave browser

### ISSUE THREAD

**Issue by marnovo** [metarmask/dom-distiller-reading-mode#17]
Although the extension works flawlessly on other Chromium-based browsers (tried on Chrome, Opera, Vivaldi), on [Brave](http://brave.com) the loading spinner keeps on indefinitely. Once you active the extension again it goes back normally to the original page.

**Comment by metarmask** [comment]
This is #4. Brave blocks third-party cookies by default and extensions aren't exempt from this. In #4 there's both a workaround and a link where you can vote for a Chromium issue to get this fixed for others.

**Comment by metarmask** [comment]
Looks like you don't need to vote for the issue. Instead just wait for Brave to update in about 23 days.
